import os
import traceback
from datetime import datetime
from flask import Flask, request, jsonify, send_from_directory, send_file
from flask_cors import CORS
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__, static_folder="ui")
CORS(app)

agent_executor = None


def get_agent():
    global agent_executor
    if agent_executor is None:
        from agent import build_agent
        agent_executor = build_agent()
    return agent_executor


@app.route("/")
def index():
    return send_from_directory("ui", "index.html")


@app.route("/health", methods=["GET"])
def health():
    api_key = os.getenv("OPENAI_API_KEY", "")
    if not api_key or api_key.startswith("<") or api_key == "PASTE_YOUR_NEW_KEY_HERE":
        return jsonify({"status": "error", "message": "OPENAI_API_KEY not set in .env file"}), 500
    return jsonify({"status": "ok", "message": "Backend connected. Agent is ready!"})


def _build_pdf(content, title="Document"):
    """Build a styled PDF and return its download URL."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    os.makedirs("outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"{title.replace(' ','_')}_{timestamp}.pdf"
    filepath  = f"outputs/{filename}"

    doc    = SimpleDocTemplate(filepath, pagesize=A4,
                               leftMargin=2.5*cm, rightMargin=2.5*cm,
                               topMargin=2.5*cm, bottomMargin=2.5*cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("T", parent=styles["Normal"], fontSize=18,
                                 fontName="Helvetica-Bold",
                                 textColor=colors.HexColor("#2c2c6c"),
                                 spaceAfter=6, alignment=TA_CENTER)
    sub_style   = ParagraphStyle("S", parent=styles["Normal"], fontSize=10,
                                 textColor=colors.HexColor("#888888"),
                                 spaceAfter=4, alignment=TA_CENTER)
    body_style  = ParagraphStyle("B", parent=styles["Normal"], fontSize=11,
                                 leading=18, textColor=colors.HexColor("#222222"),
                                 spaceAfter=10, alignment=TA_LEFT)
    foot_style  = ParagraphStyle("F", parent=styles["Normal"], fontSize=8,
                                 textColor=colors.grey, alignment=TA_CENTER)

    story = [
        Paragraph(title.replace("_", " "), title_style),
        Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y')}", sub_style),
        Spacer(1, 0.3*cm),
        HRFlowable(width="100%", thickness=1.5,
                   color=colors.HexColor("#6c63ff"), spaceAfter=14),
    ]
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.3*cm))
        else:
            safe = line.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
            story.append(Paragraph(safe, body_style))
    story += [
        Spacer(1, 0.5*cm),
        HRFlowable(width="100%", thickness=0.5,
                   color=colors.HexColor("#cccccc"), spaceAfter=8),
        Paragraph("Generated by Job Application AI Agent", foot_style)
    ]
    doc.build(story)
    return f"/download-pdf/{filename}"


@app.route("/chat", methods=["POST"])
def chat():
    data = request.json or {}
    user_message = data.get("message", "").strip()
    if not user_message:
        return jsonify({"error": "Empty message"}), 400

    api_key = os.getenv("OPENAI_API_KEY", "")
    if not api_key or api_key.startswith("<"):
        return jsonify({"error": "OPENAI_API_KEY not set. Add your key to the .env file."}), 500

    # Inject uploaded resume + job context automatically
    context_prefix = ""
    resume_text = app.config.get("RESUME_TEXT", "")
    job_text    = app.config.get("JOB_TEXT", "")
    if resume_text:
        context_prefix += f"[RESUME CONTENT]:\n{resume_text[:3000]}\n\n"
    if job_text:
        context_prefix += f"[JOB DESCRIPTION]:\n{job_text[:3000]}\n\n"
    full_message = context_prefix + user_message if context_prefix else user_message

    try:
        agent = get_agent()
        response = agent.invoke(
            {"input": full_message},
            config={"configurable": {"session_id": "ui-session"}}
        )
        output = response["output"]
        app.config["LAST_AGENT_OUTPUT"] = output

        # Auto-generate PDF if response looks like a cover letter
        pdf_url = None
        cover_keywords = ["dear hiring", "dear recruiter", "i am writing", "cover letter", "sincerely", "yours faithfully"]
        if any(kw in output.lower() for kw in cover_keywords):
            try:
                pdf_url = _build_pdf(output, "Cover_Letter")
            except Exception:
                pass

        return jsonify({"response": output, "pdf_url": pdf_url})
    except Exception as e:
        traceback.print_exc()
        err = str(e)
        if "401" in err or "invalid_api_key" in err or "Incorrect API key" in err:
            return jsonify({"error": "Invalid OpenAI API key. Get a new one at platform.openai.com/api-keys"}), 401
        if "insufficient_quota" in err:
            return jsonify({"error": "OpenAI quota exceeded. Check billing at platform.openai.com"}), 402
        return jsonify({"error": f"Agent error: {err}"}), 500


@app.route("/report", methods=["GET"])
def report():
    try:
        from src.tracker_tools import get_application_report
        result = get_application_report.invoke("all")
        return jsonify({"report": result})
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


@app.route("/upload-resume", methods=["POST"])
def upload_resume():
    if "file" not in request.files:
        return jsonify({"error": "No file provided"}), 400
    file = request.files["file"]
    if not file.filename:
        return jsonify({"error": "Empty filename"}), 400
    os.makedirs("data", exist_ok=True)
    path = f"data/{file.filename}"
    file.save(path)

    # Auto-parse and store resume text in session context
    try:
        from src.resume_tools import parse_resume
        text = parse_resume.invoke(path)
        app.config["RESUME_TEXT"] = text
        app.config["RESUME_PATH"] = path
    except Exception as e:
        return jsonify({"error": f"File saved but parse failed: {e}"}), 500

    return jsonify({"message": f"Resume '{file.filename}' uploaded and parsed!", "path": path})


@app.route("/upload-job", methods=["POST"])
def upload_job():
    # Handle file upload
    if "file" in request.files:
        file = request.files["file"]
        if not file.filename:
            return jsonify({"error": "Empty filename"}), 400
        os.makedirs("data", exist_ok=True)
        path = f"data/{file.filename}"
        file.save(path)
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            text = f.read()
    # Handle plain text paste
    elif request.json and request.json.get("text"):
        text = request.json["text"]
        os.makedirs("data", exist_ok=True)
        path = "data/job_description.txt"
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
    else:
        return jsonify({"error": "No file or text provided"}), 400

    app.config["JOB_TEXT"] = text
    app.config["JOB_PATH"] = path
    return jsonify({"message": "Job description uploaded successfully!", "path": path, "preview": text[:300]})


@app.route("/context", methods=["GET"])
def context():
    """Return what resume and job are currently loaded."""
    return jsonify({
        "resume_path": app.config.get("RESUME_PATH", None),
        "job_path":    app.config.get("JOB_PATH", None),
    })


@app.route("/download-pdf/<filename>", methods=["GET"])
def download_pdf_file(filename):
    return send_file(f"outputs/{filename}", as_attachment=True,
                     download_name=filename, mimetype="application/pdf")


@app.route("/generate-pdf", methods=["POST"])
def generate_pdf():
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    data     = request.json or {}
    doc_type = data.get("type", "cover_letter")   # cover_letter | report
    content  = data.get("content", "").strip()
    title    = data.get("title", "Document")

    if not content:
        # Auto-use last agent output stored in config
        content = app.config.get("LAST_AGENT_OUTPUT", "")
    if not content:
        return jsonify({"error": "No content to generate PDF from. Ask the agent first."}), 400

    os.makedirs("outputs", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"{doc_type}_{timestamp}.pdf"
    filepath  = f"outputs/{filename}"

    doc    = SimpleDocTemplate(filepath, pagesize=A4,
                               leftMargin=2.5*cm, rightMargin=2.5*cm,
                               topMargin=2.5*cm, bottomMargin=2.5*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", parent=styles["Normal"],
                                 fontSize=18, fontName="Helvetica-Bold",
                                 textColor=colors.HexColor("#2c2c6c"),
                                 spaceAfter=6, alignment=TA_CENTER)
    sub_style   = ParagraphStyle("Sub", parent=styles["Normal"],
                                 fontSize=10, textColor=colors.HexColor("#888888"),
                                 spaceAfter=4, alignment=TA_CENTER)
    body_style  = ParagraphStyle("Body", parent=styles["Normal"],
                                 fontSize=11, leading=18,
                                 textColor=colors.HexColor("#222222"),
                                 spaceAfter=10, alignment=TA_LEFT)

    story = [
        Paragraph(title, title_style),
        Paragraph(f"Generated on {datetime.now().strftime('%B %d, %Y')}", sub_style),
        Spacer(1, 0.3*cm),
        HRFlowable(width="100%", thickness=1.5,
                   color=colors.HexColor("#6c63ff"), spaceAfter=14),
    ]

    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.3*cm))
        else:
            safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, body_style))

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#cccccc"), spaceAfter=8))
    story.append(Paragraph("Generated by Job Application AI Agent",
                           ParagraphStyle("Footer", parent=styles["Normal"],
                                          fontSize=8, textColor=colors.grey,
                                          alignment=TA_CENTER)))
    doc.build(story)
    return send_file(filepath, as_attachment=True,
                     download_name=filename, mimetype="application/pdf")


if __name__ == "__main__":
    from waitress import serve
    PORT = 8000
    print("\n========================================")
    print("  Job Application AI Agent")
    print("========================================")
    api_key = os.getenv("OPENAI_API_KEY", "")
    if not api_key or api_key.startswith("<"):
        print("  WARNING: OPENAI_API_KEY not set in .env!")
    else:
        print(f"  API Key: {api_key[:14]}...")
    print(f"  Open browser: http://localhost:{PORT}")
    print("========================================\n")
    serve(app, host="127.0.0.1", port=PORT)
